# Generated by Django 5.0.8 on 2024-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('anio_lanzamineto', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('poster', models.CharField(max_length=255)),
            ],
        ),
    ]
