# Generated by Django 5.0.8 on 2024-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
        ),
    ]
